
#:schema node_modules/wrangler/config-schema.json
name = "WORKER-NAME"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "20f14acbd56a46f9b9d575dc102b8f78" }
]
