
  #"$schema": "node_modules/wrangler/config-schema.json",
  name": "WORKER-NAME",
  main": "src/index.ts",
  compatibility_date": "2025-02-04",
  compatibility_flags = ["nodejs_compat"]

  // Add this to your wrangler.jsonc
  "kv_namespaces": [
    {
      "binding": "KV",
      "id": "20f14acbd56a46f9b9d575dc102b8f78",
      
      // Optional: preview_id used when running `wrangler dev` for local dev
      "preview_id": "<ID_OF_PREVIEW_KV_NAMESPACE_FOR_LOCAL_DEVELOPMENT>"
    }
  ]

